config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", 
    omniauth_callbacks: "omniauth_callbacks" }
  
  resources :users, only: [:index, :show]
  resources :users do
    member do
      get :followeds, :followers, :newsfeed, :liked_pictures
    end
  end

  resources :pictures,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes,       only: [:create, :destroy]

  get 'help/instructions'
  get 'help/about'
  get 'help/contact'

  root :to => "application#index" 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF(cross-site request forgery) attacks by raising an exception.
  # Include the security token in requests and verify it on the server.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Brak dostępu!"
    redirect_to root_path
  end

  def index
  	if signed_in?
  		@picture = current_user.pictures.build
      @last_items = current_user.pictures.limit(6)
      @liked_items = current_user.liked_pictures.limit(6)
      @followed_items = current_user.feed.limit(6)
  	end
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nick <<:name
    devise_parameter_sanitizer.for(:account_update) << :nick << :name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 
end

app/views/application/_add_image.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Dodaj zdjęcie</h4>
  </div>
  <div class="panel-body">
	<%= form_for(@picture) do |f| %>
	
	  <div class="form-group">
	  	<%= f.label :image, "Zdjęcie" %>
	    <%= f.file_field :image, class: "form-control"%>
	  </div>
	  <div class="form-group">
	  	<%= f.label :title, "Opis"%>
	    <%= f.text_field :title, autocomplete: "off", class: "form-control" %>
	  </div>
	  <%= f.submit "Prześlij", class: "btn btn-primary add" %>
	<% end %>
  </div>
</div>

app/views/application/_alert.html.erb
<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/application/_errors.html.erb
<% if ! object.errors.empty? %>
  <% sentence = I18n.t('errors.messages.not_saved',
    count: object.errors.count,
    resource: object.class.model_name.human.downcase) %>
  
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4><%= sentence %></h4>
    <% object.errors.full_messages.map do |msg| %>
      <%= content_tag(:p, msg) %>
    <% end %>
  </div>
<% end %>

app/views/application/_follow_gallery.html.erb
<% for i in (0 .. @users.count/6) %>
  <div class="row">
    <% for j in (0..5) %>
      <% if (!@users[6*i+j].nil?) %>
        <div class="col-md-2 col-xs-4">
          <div class="thumbnail thumbnail_gallery">
            <%= link_to (gravatar_for_gallery @users[6*i+j]), @users[6*i+j] %>
            <h4><%= @users[6*i+j].nick %></h4>
          </div>
        </div>
      <% else %>
        <% break; %>
      <% end %>
    <% end %>  
  </div>
  <hr/>     
<% end %>  

app/views/application/_nav.html.erb
<div class="container">
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="<%= root_path %>" class="navbar-brand" id="nav_logo"> 
          <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>  IMG 
        </a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
            <li>
              <%= link_to "Rejestracja", new_user_registration_path %> 
            </li>
            <li>
              <%= link_to "Zaloguj", new_user_session_path %>
            </li>
            <% else %>
            <li class="dropdown">
              <%= link_to "#", class: 'dropdown-toggle', "data-toggle" => "dropdown", role: "button", "aria-expanded" => "false" do %>
                <%= current_user.nick %> <span class="caret">
              <% end %>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "Profil", user_path(current_user) %>
                </li>
                <li>
                  <%= link_to "Edytuj dane", edit_user_registration_path(current_user) %>
                </li>
                <li>
                  <%= link_to "Ulubione zdjęcia", liked_pictures_user_path(current_user) %>
                </li>
                <li class="divider"></li> 
                <li>
                  <%= link_to "Wyloguj", destroy_user_session_path, :method=>'delete' %></li>
                </li>
              </ul>

            </li>
            <li>
              <%= link_to "Prześlij zdjęcie", root_path, style: "font-weight:bold;" %>
            </li>
            <li>
              <%= link_to "Nowości", newsfeed_user_path(current_user) %>
            </li>
          <% end %>
          <li>
            <%= link_to "Użytkownicy", users_path %>
          </li>
                <li class="dropdown">
                  <%= link_to "#", class: 'dropdown-toggle', "data-toggle" => "dropdown", role: "button", "aria-expanded" => "false" do %>
                  Pomoc<span class="caret">
              <% end %>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "O aplikacji", help_about_path %>
                </li>
                <li>
                  <%= link_to "Instrukcja obsługi", help_instructions_path %>
                </li>
                <li>
                  <%= link_to "Kontakt", help_contact_path %>
                </li>
              </ul>

            </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
</div>

app/views/application/_profile.html.erb
<div class="col-lg-2 pull-left">
  <div  class="media">
    <div class="media-left media-middle">
    	<%= gravatar_for_logo @user %>
      <%= render 'follow' if signed_in? %>
    </div>
  </div>
</div>
<div class="col-lg-5">
  <div class="media">
    <div class="media-left media-middle">
	    <h1 class="profil"><%= @user .nick %></h1>
	    <h2 class="profil">
	      <%if !@user.name.blank? %>
	        <%= @user.name  %>
	      <% end %> 
	    </h2>
	    <p class="last_log"> Ostatnie logowanie: <%= localize(@user.last_sign_in_at, :format => :short) %></p>
   </div>
  </div>
</div>

app/views/application/_shortcuts.html.erb
<% @title = link_to user_path(current_user) do %>
 <h4> Moje najnowsze zdjęcia </h4>
<% end %>
<% @flag = "title" %>
<% @pictures = @last_items %>
<%= render 'six_pictures' %>

<% @title = link_to user_path(current_user) do%>
  <h4> Ulubione zdjęcia </h4>
<% end %>
<% @flag = "liked_at" %>
<% @pictures = @liked_items %>
<%= render 'six_pictures' %>

<% @title = link_to newsfeed_user_path(current_user) do %>
  <h4> Najnowsze zdjęcia obserowanych użytkowników </h4>
<% end %>
<% @flag = "created_at" %>
<% @pictures = @followed_items %>
<%= render 'six_pictures' %>

app/views/application/_six_pictures.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @title %>
  </div>
  <div class="panel-body">
  	<div class="row">
      <% if @pictures.count == 0 %>
        <p class="center"> Aktualnie brak zdjęć do wyświetlenia. </p>
      <% else %>
    	  <% @pictures.each do |i| %>
            <% if @flag == "title" %>
                  <% description = i.title %>
            <% else %>
               <%if @flag == "liked_at" %>
                    <% description = 'Oznaczone ' + time_ago_in_words(i.likes.find_by(user_id: current_user.id).created_at) + ' temu' %>
              <% else %>
                <%if @flag == "created_at" %>
                      <% description = 'Dodane ' + time_ago_in_words(i.created_at) + ' temu' %>
                <% else %>
                      <% description = '' %>
                <% end %>
              <% end %>
            <% end %>
  	  	  <div class="col-md-2 col-xs-4">
  		  	  <div class="thumbnail thumbnail_gallery">
  		        <a href="<%= user_path current_user %>" title="<%= description %>" alt="img">
  		           <%= image_tag i.image.url(:thumb), class: 'thumbnail' %>
  		       </a>
  		      </div>
  		  </div>
        <% end %>
      <% end %>
  	</div>
  </div>
</div>

app/views/application/_stats.html.erb
<div class="col-lg-5 ">
	<div class="btn-group pull-right stats" role="group">
	  <a class="btn btn-default stat stat_pictures" href="<%= user_path (@user) %>">
	    <span class="bold"> <%= @user.pictures.count %> </span><br/>zdjęć
	  </a>
	  <a class="btn btn-default stat stat_followeds" href="<%= followeds_user_path(@user) %>">
	    <span class="bold"> <%= @user.followeds.count %> </span><br/>obserwowani
	  </a>
	  <a class="btn btn-default stat stat_followers" href="<%= followers_user_path(@user) %>">
	    <span class="bold"> <%= @user.followers.count %> </span><br/>obserwujący
	  </a>
	</div>
</div>

app/views/application/_user_gallery.html.erb
<script>
$(document).ready(function() {
  $("a.fancybox").fancybox();
});
</script>

<% for i in (0 .. @pictures.count/6) %>
  <div class="row">
    <% for j in (0..5) %>
      <% if (!@pictures[6*i+j].nil?) %>
        <div class="col-md-2 col-xs-4 col_margin">
          <div class="thumbnail thumbnail_gallery">
            <a href="<%= @pictures[6*i+j].image.url(:original) %>" title="<%= @pictures[6*i+j].title %>" alt="img" rel="gallery" class="fancybox">
              <%= image_tag @pictures[6*i+j].image.url(:thumb), class: 'thumbnail' %>
            </a>
            <div class="media">
              <div class="media-left">
                <% @pic = @pictures[6*i+j] %>
                <%= render 'users/button_like' %>
              </div>
              <div class="media-body">
                <%if signed_in? %>
                  <% if current_user.id == @user.id %>
                    <%= link_to @pictures[6*i+j], method: :delete, data: { confirm: "Czy usunąć?" }, class: "btn btn-primary btn_remove pull-right" do%>
                    <span class="glyphicon glyphicon-remove heart" aria-hidden="true"></span>
                    <% end %>
                  <% end %>
                <% end %> 
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>  
  </div> 
  <hr/>  
<% end %> 

app/views/application/index.html.erb
<% if signed_in? %>
	<%= render 'add_image' %>
	<%= render 'shortcuts' %>
<% else %>
   <% content_for :head do %>
	  <div class="center jumbotron" id="jumbotron_home">
		<h1>Dzień dobry!</h1>
		<h2>Aby móc używać aplikacji, należy się zarejestrować.</h2>

		<%= link_to "Rejestracja", new_user_registration_path, class: "btn btn-lg btn-primary btn_home" %>
 	  </div>
  <% end %>
<% end %>